trigger:
- master

pool:
  vmImage: 'macOS-10.13'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/Android.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'

- task: XamariniOS@2
  inputs:
    solutionFile: '**/*.sln'
    configuration: '$(buildConfiguration)'
    buildForSimulator: true
    packageApp: false

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'