trigger:
- master

pool:
  vmImage: 'macOS-10.13'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@1
  inputs:
    restoreSolution: '**/*.sln'